feat: Productivity Weekly(2023/10/25) pull_request_target, go, aws log
korosuke613/zenn-articles pull request #490
Opened 2023-10-27 14:07 UTC by uta8a

2023-10-30 11:44 UTC, korosuke613 requested changes
プルリクありがとうございます！
まず、ベースブランチの変更に伴い僕の方で rebase して再プッシュしました。

内容としては特に問題なかったのですが、GitHub Actions で怒られている通り、textlint の `原則として、全角文字と半角文字の間にスペースを入れます。 (ja-spacing/ja-space-between-half-and-full-width)` というルールに複数引っかかってしまっているため、修正していただきたいです。

具体的には、`npx textlint --fix ./articles/productivity-weekly-20231025.md` で自動修正できます。

2023-10-31 00:59 UTC, uta8a commented
@korosuke613 ありがとうございます！Contributionのところ読んでなかったです、すみません...

textlintをかけて修正しました(commitは一つにまとめました)

余談なんですが、`npm ci` しておかないとtextlintって効かないんですね、npxで動かすからてっきりなにもしなくても動くのかと思っていました。あまりハマらないパターンだとは思いますがメモしておきます。

```bash
# npx ci しない状態でtextlintをかけようとする
$ npx textlint ./articles/productivity-weekly-20231025.md

== No rules found, textlint hasn’t done anything ==

Possible reasons:
* Your textlint config file has no rules.
* You have no config file and you aren’t passing rules via command line.
* Your textlint config has a syntax error.

=> How to set up rules?
https://github.com/textlint/textlint/blob/master/docs/configuring.md

# npm ci すると動く
```

2023-10-31 01:26 UTC, korosuke613 approved these changes
LGTM!

2023-10-31 01:27 UTC, korosuke613 commented
@uta8a 
対応ありがとうございました！
コントリビューションの記述は昨日追加したので気にしないでください。

textlintがおかしい件は...ちょっとわからないですね〜
`npm ci`で直ったのなら`node_modules`がおかしくなってたのかも

2023-10-31 01:28 UTC, merged